/* =========================================================================
   Full National Dex (Gen 1-9, 1025 Pokémon) via PokéAPI.
   tier: 'legendary' = legendary or mythical (milestone rewards only).
   Artwork/sprites/cries hot-linked or bundled — personal/educational
   fan use only, never commercial.
   ========================================================================= */
const POKEMON = [
  { id: 1, name: 'Bulbasaur', tier: 'common' },
  { id: 2, name: 'Ivysaur', tier: 'common' },
  { id: 3, name: 'Venusaur', tier: 'common' },
  { id: 4, name: 'Charmander', tier: 'common' },
  { id: 5, name: 'Charmeleon', tier: 'common' },
  { id: 6, name: 'Charizard', tier: 'common' },
  { id: 7, name: 'Squirtle', tier: 'common' },
  { id: 8, name: 'Wartortle', tier: 'common' },
  { id: 9, name: 'Blastoise', tier: 'common' },
  { id: 10, name: 'Caterpie', tier: 'common' },
  { id: 11, name: 'Metapod', tier: 'common' },
  { id: 12, name: 'Butterfree', tier: 'common' },
  { id: 13, name: 'Weedle', tier: 'common' },
  { id: 14, name: 'Kakuna', tier: 'common' },
  { id: 15, name: 'Beedrill', tier: 'common' },
  { id: 16, name: 'Pidgey', tier: 'common' },
  { id: 17, name: 'Pidgeotto', tier: 'common' },
  { id: 18, name: 'Pidgeot', tier: 'common' },
  { id: 19, name: 'Rattata', tier: 'common' },
  { id: 20, name: 'Raticate', tier: 'common' },
  { id: 21, name: 'Spearow', tier: 'common' },
  { id: 22, name: 'Fearow', tier: 'common' },
  { id: 23, name: 'Ekans', tier: 'common' },
  { id: 24, name: 'Arbok', tier: 'common' },
  { id: 25, name: 'Pikachu', tier: 'common' },
  { id: 26, name: 'Raichu', tier: 'common' },
  { id: 27, name: 'Sandshrew', tier: 'common' },
  { id: 28, name: 'Sandslash', tier: 'common' },
  { id: 29, name: 'Nidoran F', tier: 'common' },
  { id: 30, name: 'Nidorina', tier: 'common' },
  { id: 31, name: 'Nidoqueen', tier: 'common' },
  { id: 32, name: 'Nidoran M', tier: 'common' },
  { id: 33, name: 'Nidorino', tier: 'common' },
  { id: 34, name: 'Nidoking', tier: 'common' },
  { id: 35, name: 'Clefairy', tier: 'common' },
  { id: 36, name: 'Clefable', tier: 'common' },
  { id: 37, name: 'Vulpix', tier: 'common' },
  { id: 38, name: 'Ninetales', tier: 'common' },
  { id: 39, name: 'Jigglypuff', tier: 'common' },
  { id: 40, name: 'Wigglytuff', tier: 'common' },
  { id: 41, name: 'Zubat', tier: 'common' },
  { id: 42, name: 'Golbat', tier: 'common' },
  { id: 43, name: 'Oddish', tier: 'common' },
  { id: 44, name: 'Gloom', tier: 'common' },
  { id: 45, name: 'Vileplume', tier: 'common' },
  { id: 46, name: 'Paras', tier: 'common' },
  { id: 47, name: 'Parasect', tier: 'common' },
  { id: 48, name: 'Venonat', tier: 'common' },
  { id: 49, name: 'Venomoth', tier: 'common' },
  { id: 50, name: 'Diglett', tier: 'common' },
  { id: 51, name: 'Dugtrio', tier: 'common' },
  { id: 52, name: 'Meowth', tier: 'common' },
  { id: 53, name: 'Persian', tier: 'common' },
  { id: 54, name: 'Psyduck', tier: 'common' },
  { id: 55, name: 'Golduck', tier: 'common' },
  { id: 56, name: 'Mankey', tier: 'common' },
  { id: 57, name: 'Primeape', tier: 'common' },
  { id: 58, name: 'Growlithe', tier: 'common' },
  { id: 59, name: 'Arcanine', tier: 'common' },
  { id: 60, name: 'Poliwag', tier: 'common' },
  { id: 61, name: 'Poliwhirl', tier: 'common' },
  { id: 62, name: 'Poliwrath', tier: 'common' },
  { id: 63, name: 'Abra', tier: 'common' },
  { id: 64, name: 'Kadabra', tier: 'common' },
  { id: 65, name: 'Alakazam', tier: 'common' },
  { id: 66, name: 'Machop', tier: 'common' },
  { id: 67, name: 'Machoke', tier: 'common' },
  { id: 68, name: 'Machamp', tier: 'common' },
  { id: 69, name: 'Bellsprout', tier: 'common' },
  { id: 70, name: 'Weepinbell', tier: 'common' },
  { id: 71, name: 'Victreebel', tier: 'common' },
  { id: 72, name: 'Tentacool', tier: 'common' },
  { id: 73, name: 'Tentacruel', tier: 'common' },
  { id: 74, name: 'Geodude', tier: 'common' },
  { id: 75, name: 'Graveler', tier: 'common' },
  { id: 76, name: 'Golem', tier: 'common' },
  { id: 77, name: 'Ponyta', tier: 'common' },
  { id: 78, name: 'Rapidash', tier: 'common' },
  { id: 79, name: 'Slowpoke', tier: 'common' },
  { id: 80, name: 'Slowbro', tier: 'common' },
  { id: 81, name: 'Magnemite', tier: 'common' },
  { id: 82, name: 'Magneton', tier: 'common' },
  { id: 83, name: 'Farfetchd', tier: 'common' },
  { id: 84, name: 'Doduo', tier: 'common' },
  { id: 85, name: 'Dodrio', tier: 'common' },
  { id: 86, name: 'Seel', tier: 'common' },
  { id: 87, name: 'Dewgong', tier: 'common' },
  { id: 88, name: 'Grimer', tier: 'common' },
  { id: 89, name: 'Muk', tier: 'common' },
  { id: 90, name: 'Shellder', tier: 'common' },
  { id: 91, name: 'Cloyster', tier: 'common' },
  { id: 92, name: 'Gastly', tier: 'common' },
  { id: 93, name: 'Haunter', tier: 'common' },
  { id: 94, name: 'Gengar', tier: 'common' },
  { id: 95, name: 'Onix', tier: 'common' },
  { id: 96, name: 'Drowzee', tier: 'common' },
  { id: 97, name: 'Hypno', tier: 'common' },
  { id: 98, name: 'Krabby', tier: 'common' },
  { id: 99, name: 'Kingler', tier: 'common' },
  { id: 100, name: 'Voltorb', tier: 'common' },
  { id: 101, name: 'Electrode', tier: 'common' },
  { id: 102, name: 'Exeggcute', tier: 'common' },
  { id: 103, name: 'Exeggutor', tier: 'common' },
  { id: 104, name: 'Cubone', tier: 'common' },
  { id: 105, name: 'Marowak', tier: 'common' },
  { id: 106, name: 'Hitmonlee', tier: 'common' },
  { id: 107, name: 'Hitmonchan', tier: 'common' },
  { id: 108, name: 'Lickitung', tier: 'common' },
  { id: 109, name: 'Koffing', tier: 'common' },
  { id: 110, name: 'Weezing', tier: 'common' },
  { id: 111, name: 'Rhyhorn', tier: 'common' },
  { id: 112, name: 'Rhydon', tier: 'common' },
  { id: 113, name: 'Chansey', tier: 'common' },
  { id: 114, name: 'Tangela', tier: 'common' },
  { id: 115, name: 'Kangaskhan', tier: 'common' },
  { id: 116, name: 'Horsea', tier: 'common' },
  { id: 117, name: 'Seadra', tier: 'common' },
  { id: 118, name: 'Goldeen', tier: 'common' },
  { id: 119, name: 'Seaking', tier: 'common' },
  { id: 120, name: 'Staryu', tier: 'common' },
  { id: 121, name: 'Starmie', tier: 'common' },
  { id: 122, name: 'Mr. Mime', tier: 'common' },
  { id: 123, name: 'Scyther', tier: 'common' },
  { id: 124, name: 'Jynx', tier: 'common' },
  { id: 125, name: 'Electabuzz', tier: 'common' },
  { id: 126, name: 'Magmar', tier: 'common' },
  { id: 127, name: 'Pinsir', tier: 'common' },
  { id: 128, name: 'Tauros', tier: 'common' },
  { id: 129, name: 'Magikarp', tier: 'common' },
  { id: 130, name: 'Gyarados', tier: 'common' },
  { id: 131, name: 'Lapras', tier: 'common' },
  { id: 132, name: 'Ditto', tier: 'common' },
  { id: 133, name: 'Eevee', tier: 'common' },
  { id: 134, name: 'Vaporeon', tier: 'common' },
  { id: 135, name: 'Jolteon', tier: 'common' },
  { id: 136, name: 'Flareon', tier: 'common' },
  { id: 137, name: 'Porygon', tier: 'common' },
  { id: 138, name: 'Omanyte', tier: 'common' },
  { id: 139, name: 'Omastar', tier: 'common' },
  { id: 140, name: 'Kabuto', tier: 'common' },
  { id: 141, name: 'Kabutops', tier: 'common' },
  { id: 142, name: 'Aerodactyl', tier: 'common' },
  { id: 143, name: 'Snorlax', tier: 'common' },
  { id: 144, name: 'Articuno', tier: 'legendary' },
  { id: 145, name: 'Zapdos', tier: 'legendary' },
  { id: 146, name: 'Moltres', tier: 'legendary' },
  { id: 147, name: 'Dratini', tier: 'common' },
  { id: 148, name: 'Dragonair', tier: 'common' },
  { id: 149, name: 'Dragonite', tier: 'common' },
  { id: 150, name: 'Mewtwo', tier: 'legendary' },
  { id: 151, name: 'Mew', tier: 'legendary' },
  { id: 152, name: 'Chikorita', tier: 'common' },
  { id: 153, name: 'Bayleef', tier: 'common' },
  { id: 154, name: 'Meganium', tier: 'common' },
  { id: 155, name: 'Cyndaquil', tier: 'common' },
  { id: 156, name: 'Quilava', tier: 'common' },
  { id: 157, name: 'Typhlosion', tier: 'common' },
  { id: 158, name: 'Totodile', tier: 'common' },
  { id: 159, name: 'Croconaw', tier: 'common' },
  { id: 160, name: 'Feraligatr', tier: 'common' },
  { id: 161, name: 'Sentret', tier: 'common' },
  { id: 162, name: 'Furret', tier: 'common' },
  { id: 163, name: 'Hoothoot', tier: 'common' },
  { id: 164, name: 'Noctowl', tier: 'common' },
  { id: 165, name: 'Ledyba', tier: 'common' },
  { id: 166, name: 'Ledian', tier: 'common' },
  { id: 167, name: 'Spinarak', tier: 'common' },
  { id: 168, name: 'Ariados', tier: 'common' },
  { id: 169, name: 'Crobat', tier: 'common' },
  { id: 170, name: 'Chinchou', tier: 'common' },
  { id: 171, name: 'Lanturn', tier: 'common' },
  { id: 172, name: 'Pichu', tier: 'common' },
  { id: 173, name: 'Cleffa', tier: 'common' },
  { id: 174, name: 'Igglybuff', tier: 'common' },
  { id: 175, name: 'Togepi', tier: 'common' },
  { id: 176, name: 'Togetic', tier: 'common' },
  { id: 177, name: 'Natu', tier: 'common' },
  { id: 178, name: 'Xatu', tier: 'common' },
  { id: 179, name: 'Mareep', tier: 'common' },
  { id: 180, name: 'Flaaffy', tier: 'common' },
  { id: 181, name: 'Ampharos', tier: 'common' },
  { id: 182, name: 'Bellossom', tier: 'common' },
  { id: 183, name: 'Marill', tier: 'common' },
  { id: 184, name: 'Azumarill', tier: 'common' },
  { id: 185, name: 'Sudowoodo', tier: 'common' },
  { id: 186, name: 'Politoed', tier: 'common' },
  { id: 187, name: 'Hoppip', tier: 'common' },
  { id: 188, name: 'Skiploom', tier: 'common' },
  { id: 189, name: 'Jumpluff', tier: 'common' },
  { id: 190, name: 'Aipom', tier: 'common' },
  { id: 191, name: 'Sunkern', tier: 'common' },
  { id: 192, name: 'Sunflora', tier: 'common' },
  { id: 193, name: 'Yanma', tier: 'common' },
  { id: 194, name: 'Wooper', tier: 'common' },
  { id: 195, name: 'Quagsire', tier: 'common' },
  { id: 196, name: 'Espeon', tier: 'common' },
  { id: 197, name: 'Umbreon', tier: 'common' },
  { id: 198, name: 'Murkrow', tier: 'common' },
  { id: 199, name: 'Slowking', tier: 'common' },
  { id: 200, name: 'Misdreavus', tier: 'common' },
  { id: 201, name: 'Unown', tier: 'common' },
  { id: 202, name: 'Wobbuffet', tier: 'common' },
  { id: 203, name: 'Girafarig', tier: 'common' },
  { id: 204, name: 'Pineco', tier: 'common' },
  { id: 205, name: 'Forretress', tier: 'common' },
  { id: 206, name: 'Dunsparce', tier: 'common' },
  { id: 207, name: 'Gligar', tier: 'common' },
  { id: 208, name: 'Steelix', tier: 'common' },
  { id: 209, name: 'Snubbull', tier: 'common' },
  { id: 210, name: 'Granbull', tier: 'common' },
  { id: 211, name: 'Qwilfish', tier: 'common' },
  { id: 212, name: 'Scizor', tier: 'common' },
  { id: 213, name: 'Shuckle', tier: 'common' },
  { id: 214, name: 'Heracross', tier: 'common' },
  { id: 215, name: 'Sneasel', tier: 'common' },
  { id: 216, name: 'Teddiursa', tier: 'common' },
  { id: 217, name: 'Ursaring', tier: 'common' },
  { id: 218, name: 'Slugma', tier: 'common' },
  { id: 219, name: 'Magcargo', tier: 'common' },
  { id: 220, name: 'Swinub', tier: 'common' },
  { id: 221, name: 'Piloswine', tier: 'common' },
  { id: 222, name: 'Corsola', tier: 'common' },
  { id: 223, name: 'Remoraid', tier: 'common' },
  { id: 224, name: 'Octillery', tier: 'common' },
  { id: 225, name: 'Delibird', tier: 'common' },
  { id: 226, name: 'Mantine', tier: 'common' },
  { id: 227, name: 'Skarmory', tier: 'common' },
  { id: 228, name: 'Houndour', tier: 'common' },
  { id: 229, name: 'Houndoom', tier: 'common' },
  { id: 230, name: 'Kingdra', tier: 'common' },
  { id: 231, name: 'Phanpy', tier: 'common' },
  { id: 232, name: 'Donphan', tier: 'common' },
  { id: 233, name: 'Porygon2', tier: 'common' },
  { id: 234, name: 'Stantler', tier: 'common' },
  { id: 235, name: 'Smeargle', tier: 'common' },
  { id: 236, name: 'Tyrogue', tier: 'common' },
  { id: 237, name: 'Hitmontop', tier: 'common' },
  { id: 238, name: 'Smoochum', tier: 'common' },
  { id: 239, name: 'Elekid', tier: 'common' },
  { id: 240, name: 'Magby', tier: 'common' },
  { id: 241, name: 'Miltank', tier: 'common' },
  { id: 242, name: 'Blissey', tier: 'common' },
  { id: 243, name: 'Raikou', tier: 'legendary' },
  { id: 244, name: 'Entei', tier: 'legendary' },
  { id: 245, name: 'Suicune', tier: 'legendary' },
  { id: 246, name: 'Larvitar', tier: 'common' },
  { id: 247, name: 'Pupitar', tier: 'common' },
  { id: 248, name: 'Tyranitar', tier: 'common' },
  { id: 249, name: 'Lugia', tier: 'legendary' },
  { id: 250, name: 'Ho-Oh', tier: 'legendary' },
  { id: 251, name: 'Celebi', tier: 'legendary' },
  { id: 252, name: 'Treecko', tier: 'common' },
  { id: 253, name: 'Grovyle', tier: 'common' },
  { id: 254, name: 'Sceptile', tier: 'common' },
  { id: 255, name: 'Torchic', tier: 'common' },
  { id: 256, name: 'Combusken', tier: 'common' },
  { id: 257, name: 'Blaziken', tier: 'common' },
  { id: 258, name: 'Mudkip', tier: 'common' },
  { id: 259, name: 'Marshtomp', tier: 'common' },
  { id: 260, name: 'Swampert', tier: 'common' },
  { id: 261, name: 'Poochyena', tier: 'common' },
  { id: 262, name: 'Mightyena', tier: 'common' },
  { id: 263, name: 'Zigzagoon', tier: 'common' },
  { id: 264, name: 'Linoone', tier: 'common' },
  { id: 265, name: 'Wurmple', tier: 'common' },
  { id: 266, name: 'Silcoon', tier: 'common' },
  { id: 267, name: 'Beautifly', tier: 'common' },
  { id: 268, name: 'Cascoon', tier: 'common' },
  { id: 269, name: 'Dustox', tier: 'common' },
  { id: 270, name: 'Lotad', tier: 'common' },
  { id: 271, name: 'Lombre', tier: 'common' },
  { id: 272, name: 'Ludicolo', tier: 'common' },
  { id: 273, name: 'Seedot', tier: 'common' },
  { id: 274, name: 'Nuzleaf', tier: 'common' },
  { id: 275, name: 'Shiftry', tier: 'common' },
  { id: 276, name: 'Taillow', tier: 'common' },
  { id: 277, name: 'Swellow', tier: 'common' },
  { id: 278, name: 'Wingull', tier: 'common' },
  { id: 279, name: 'Pelipper', tier: 'common' },
  { id: 280, name: 'Ralts', tier: 'common' },
  { id: 281, name: 'Kirlia', tier: 'common' },
  { id: 282, name: 'Gardevoir', tier: 'common' },
  { id: 283, name: 'Surskit', tier: 'common' },
  { id: 284, name: 'Masquerain', tier: 'common' },
  { id: 285, name: 'Shroomish', tier: 'common' },
  { id: 286, name: 'Breloom', tier: 'common' },
  { id: 287, name: 'Slakoth', tier: 'common' },
  { id: 288, name: 'Vigoroth', tier: 'common' },
  { id: 289, name: 'Slaking', tier: 'common' },
  { id: 290, name: 'Nincada', tier: 'common' },
  { id: 291, name: 'Ninjask', tier: 'common' },
  { id: 292, name: 'Shedinja', tier: 'common' },
  { id: 293, name: 'Whismur', tier: 'common' },
  { id: 294, name: 'Loudred', tier: 'common' },
  { id: 295, name: 'Exploud', tier: 'common' },
  { id: 296, name: 'Makuhita', tier: 'common' },
  { id: 297, name: 'Hariyama', tier: 'common' },
  { id: 298, name: 'Azurill', tier: 'common' },
  { id: 299, name: 'Nosepass', tier: 'common' },
  { id: 300, name: 'Skitty', tier: 'common' },
  { id: 301, name: 'Delcatty', tier: 'common' },
  { id: 302, name: 'Sableye', tier: 'common' },
  { id: 303, name: 'Mawile', tier: 'common' },
  { id: 304, name: 'Aron', tier: 'common' },
  { id: 305, name: 'Lairon', tier: 'common' },
  { id: 306, name: 'Aggron', tier: 'common' },
  { id: 307, name: 'Meditite', tier: 'common' },
  { id: 308, name: 'Medicham', tier: 'common' },
  { id: 309, name: 'Electrike', tier: 'common' },
  { id: 310, name: 'Manectric', tier: 'common' },
  { id: 311, name: 'Plusle', tier: 'common' },
  { id: 312, name: 'Minun', tier: 'common' },
  { id: 313, name: 'Volbeat', tier: 'common' },
  { id: 314, name: 'Illumise', tier: 'common' },
  { id: 315, name: 'Roselia', tier: 'common' },
  { id: 316, name: 'Gulpin', tier: 'common' },
  { id: 317, name: 'Swalot', tier: 'common' },
  { id: 318, name: 'Carvanha', tier: 'common' },
  { id: 319, name: 'Sharpedo', tier: 'common' },
  { id: 320, name: 'Wailmer', tier: 'common' },
  { id: 321, name: 'Wailord', tier: 'common' },
  { id: 322, name: 'Numel', tier: 'common' },
  { id: 323, name: 'Camerupt', tier: 'common' },
  { id: 324, name: 'Torkoal', tier: 'common' },
  { id: 325, name: 'Spoink', tier: 'common' },
  { id: 326, name: 'Grumpig', tier: 'common' },
  { id: 327, name: 'Spinda', tier: 'common' },
  { id: 328, name: 'Trapinch', tier: 'common' },
  { id: 329, name: 'Vibrava', tier: 'common' },
  { id: 330, name: 'Flygon', tier: 'common' },
  { id: 331, name: 'Cacnea', tier: 'common' },
  { id: 332, name: 'Cacturne', tier: 'common' },
  { id: 333, name: 'Swablu', tier: 'common' },
  { id: 334, name: 'Altaria', tier: 'common' },
  { id: 335, name: 'Zangoose', tier: 'common' },
  { id: 336, name: 'Seviper', tier: 'common' },
  { id: 337, name: 'Lunatone', tier: 'common' },
  { id: 338, name: 'Solrock', tier: 'common' },
  { id: 339, name: 'Barboach', tier: 'common' },
  { id: 340, name: 'Whiscash', tier: 'common' },
  { id: 341, name: 'Corphish', tier: 'common' },
  { id: 342, name: 'Crawdaunt', tier: 'common' },
  { id: 343, name: 'Baltoy', tier: 'common' },
  { id: 344, name: 'Claydol', tier: 'common' },
  { id: 345, name: 'Lileep', tier: 'common' },
  { id: 346, name: 'Cradily', tier: 'common' },
  { id: 347, name: 'Anorith', tier: 'common' },
  { id: 348, name: 'Armaldo', tier: 'common' },
  { id: 349, name: 'Feebas', tier: 'common' },
  { id: 350, name: 'Milotic', tier: 'common' },
  { id: 351, name: 'Castform', tier: 'common' },
  { id: 352, name: 'Kecleon', tier: 'common' },
  { id: 353, name: 'Shuppet', tier: 'common' },
  { id: 354, name: 'Banette', tier: 'common' },
  { id: 355, name: 'Duskull', tier: 'common' },
  { id: 356, name: 'Dusclops', tier: 'common' },
  { id: 357, name: 'Tropius', tier: 'common' },
  { id: 358, name: 'Chimecho', tier: 'common' },
  { id: 359, name: 'Absol', tier: 'common' },
  { id: 360, name: 'Wynaut', tier: 'common' },
  { id: 361, name: 'Snorunt', tier: 'common' },
  { id: 362, name: 'Glalie', tier: 'common' },
  { id: 363, name: 'Spheal', tier: 'common' },
  { id: 364, name: 'Sealeo', tier: 'common' },
  { id: 365, name: 'Walrein', tier: 'common' },
  { id: 366, name: 'Clamperl', tier: 'common' },
  { id: 367, name: 'Huntail', tier: 'common' },
  { id: 368, name: 'Gorebyss', tier: 'common' },
  { id: 369, name: 'Relicanth', tier: 'common' },
  { id: 370, name: 'Luvdisc', tier: 'common' },
  { id: 371, name: 'Bagon', tier: 'common' },
  { id: 372, name: 'Shelgon', tier: 'common' },
  { id: 373, name: 'Salamence', tier: 'common' },
  { id: 374, name: 'Beldum', tier: 'common' },
  { id: 375, name: 'Metang', tier: 'common' },
  { id: 376, name: 'Metagross', tier: 'common' },
  { id: 377, name: 'Regirock', tier: 'legendary' },
  { id: 378, name: 'Regice', tier: 'legendary' },
  { id: 379, name: 'Registeel', tier: 'legendary' },
  { id: 380, name: 'Latias', tier: 'legendary' },
  { id: 381, name: 'Latios', tier: 'legendary' },
  { id: 382, name: 'Kyogre', tier: 'legendary' },
  { id: 383, name: 'Groudon', tier: 'legendary' },
  { id: 384, name: 'Rayquaza', tier: 'legendary' },
  { id: 385, name: 'Jirachi', tier: 'legendary' },
  { id: 386, name: 'Deoxys', tier: 'legendary' },
  { id: 387, name: 'Turtwig', tier: 'common' },
  { id: 388, name: 'Grotle', tier: 'common' },
  { id: 389, name: 'Torterra', tier: 'common' },
  { id: 390, name: 'Chimchar', tier: 'common' },
  { id: 391, name: 'Monferno', tier: 'common' },
  { id: 392, name: 'Infernape', tier: 'common' },
  { id: 393, name: 'Piplup', tier: 'common' },
  { id: 394, name: 'Prinplup', tier: 'common' },
  { id: 395, name: 'Empoleon', tier: 'common' },
  { id: 396, name: 'Starly', tier: 'common' },
  { id: 397, name: 'Staravia', tier: 'common' },
  { id: 398, name: 'Staraptor', tier: 'common' },
  { id: 399, name: 'Bidoof', tier: 'common' },
  { id: 400, name: 'Bibarel', tier: 'common' },
  { id: 401, name: 'Kricketot', tier: 'common' },
  { id: 402, name: 'Kricketune', tier: 'common' },
  { id: 403, name: 'Shinx', tier: 'common' },
  { id: 404, name: 'Luxio', tier: 'common' },
  { id: 405, name: 'Luxray', tier: 'common' },
  { id: 406, name: 'Budew', tier: 'common' },
  { id: 407, name: 'Roserade', tier: 'common' },
  { id: 408, name: 'Cranidos', tier: 'common' },
  { id: 409, name: 'Rampardos', tier: 'common' },
  { id: 410, name: 'Shieldon', tier: 'common' },
  { id: 411, name: 'Bastiodon', tier: 'common' },
  { id: 412, name: 'Burmy', tier: 'common' },
  { id: 413, name: 'Wormadam', tier: 'common' },
  { id: 414, name: 'Mothim', tier: 'common' },
  { id: 415, name: 'Combee', tier: 'common' },
  { id: 416, name: 'Vespiquen', tier: 'common' },
  { id: 417, name: 'Pachirisu', tier: 'common' },
  { id: 418, name: 'Buizel', tier: 'common' },
  { id: 419, name: 'Floatzel', tier: 'common' },
  { id: 420, name: 'Cherubi', tier: 'common' },
  { id: 421, name: 'Cherrim', tier: 'common' },
  { id: 422, name: 'Shellos', tier: 'common' },
  { id: 423, name: 'Gastrodon', tier: 'common' },
  { id: 424, name: 'Ambipom', tier: 'common' },
  { id: 425, name: 'Drifloon', tier: 'common' },
  { id: 426, name: 'Drifblim', tier: 'common' },
  { id: 427, name: 'Buneary', tier: 'common' },
  { id: 428, name: 'Lopunny', tier: 'common' },
  { id: 429, name: 'Mismagius', tier: 'common' },
  { id: 430, name: 'Honchkrow', tier: 'common' },
  { id: 431, name: 'Glameow', tier: 'common' },
  { id: 432, name: 'Purugly', tier: 'common' },
  { id: 433, name: 'Chingling', tier: 'common' },
  { id: 434, name: 'Stunky', tier: 'common' },
  { id: 435, name: 'Skuntank', tier: 'common' },
  { id: 436, name: 'Bronzor', tier: 'common' },
  { id: 437, name: 'Bronzong', tier: 'common' },
  { id: 438, name: 'Bonsly', tier: 'common' },
  { id: 439, name: 'Mime Jr.', tier: 'common' },
  { id: 440, name: 'Happiny', tier: 'common' },
  { id: 441, name: 'Chatot', tier: 'common' },
  { id: 442, name: 'Spiritomb', tier: 'common' },
  { id: 443, name: 'Gible', tier: 'common' },
  { id: 444, name: 'Gabite', tier: 'common' },
  { id: 445, name: 'Garchomp', tier: 'common' },
  { id: 446, name: 'Munchlax', tier: 'common' },
  { id: 447, name: 'Riolu', tier: 'common' },
  { id: 448, name: 'Lucario', tier: 'common' },
  { id: 449, name: 'Hippopotas', tier: 'common' },
  { id: 450, name: 'Hippowdon', tier: 'common' },
  { id: 451, name: 'Skorupi', tier: 'common' },
  { id: 452, name: 'Drapion', tier: 'common' },
  { id: 453, name: 'Croagunk', tier: 'common' },
  { id: 454, name: 'Toxicroak', tier: 'common' },
  { id: 455, name: 'Carnivine', tier: 'common' },
  { id: 456, name: 'Finneon', tier: 'common' },
  { id: 457, name: 'Lumineon', tier: 'common' },
  { id: 458, name: 'Mantyke', tier: 'common' },
  { id: 459, name: 'Snover', tier: 'common' },
  { id: 460, name: 'Abomasnow', tier: 'common' },
  { id: 461, name: 'Weavile', tier: 'common' },
  { id: 462, name: 'Magnezone', tier: 'common' },
  { id: 463, name: 'Lickilicky', tier: 'common' },
  { id: 464, name: 'Rhyperior', tier: 'common' },
  { id: 465, name: 'Tangrowth', tier: 'common' },
  { id: 466, name: 'Electivire', tier: 'common' },
  { id: 467, name: 'Magmortar', tier: 'common' },
  { id: 468, name: 'Togekiss', tier: 'common' },
  { id: 469, name: 'Yanmega', tier: 'common' },
  { id: 470, name: 'Leafeon', tier: 'common' },
  { id: 471, name: 'Glaceon', tier: 'common' },
  { id: 472, name: 'Gliscor', tier: 'common' },
  { id: 473, name: 'Mamoswine', tier: 'common' },
  { id: 474, name: 'Porygon-Z', tier: 'common' },
  { id: 475, name: 'Gallade', tier: 'common' },
  { id: 476, name: 'Probopass', tier: 'common' },
  { id: 477, name: 'Dusknoir', tier: 'common' },
  { id: 478, name: 'Froslass', tier: 'common' },
  { id: 479, name: 'Rotom', tier: 'common' },
  { id: 480, name: 'Uxie', tier: 'legendary' },
  { id: 481, name: 'Mesprit', tier: 'legendary' },
  { id: 482, name: 'Azelf', tier: 'legendary' },
  { id: 483, name: 'Dialga', tier: 'legendary' },
  { id: 484, name: 'Palkia', tier: 'legendary' },
  { id: 485, name: 'Heatran', tier: 'legendary' },
  { id: 486, name: 'Regigigas', tier: 'legendary' },
  { id: 487, name: 'Giratina', tier: 'legendary' },
  { id: 488, name: 'Cresselia', tier: 'legendary' },
  { id: 489, name: 'Phione', tier: 'legendary' },
  { id: 490, name: 'Manaphy', tier: 'legendary' },
  { id: 491, name: 'Darkrai', tier: 'legendary' },
  { id: 492, name: 'Shaymin', tier: 'legendary' },
  { id: 493, name: 'Arceus', tier: 'legendary' },
  { id: 494, name: 'Victini', tier: 'legendary' },
  { id: 495, name: 'Snivy', tier: 'common' },
  { id: 496, name: 'Servine', tier: 'common' },
  { id: 497, name: 'Serperior', tier: 'common' },
  { id: 498, name: 'Tepig', tier: 'common' },
  { id: 499, name: 'Pignite', tier: 'common' },
  { id: 500, name: 'Emboar', tier: 'common' },
  { id: 501, name: 'Oshawott', tier: 'common' },
  { id: 502, name: 'Dewott', tier: 'common' },
  { id: 503, name: 'Samurott', tier: 'common' },
  { id: 504, name: 'Patrat', tier: 'common' },
  { id: 505, name: 'Watchog', tier: 'common' },
  { id: 506, name: 'Lillipup', tier: 'common' },
  { id: 507, name: 'Herdier', tier: 'common' },
  { id: 508, name: 'Stoutland', tier: 'common' },
  { id: 509, name: 'Purrloin', tier: 'common' },
  { id: 510, name: 'Liepard', tier: 'common' },
  { id: 511, name: 'Pansage', tier: 'common' },
  { id: 512, name: 'Simisage', tier: 'common' },
  { id: 513, name: 'Pansear', tier: 'common' },
  { id: 514, name: 'Simisear', tier: 'common' },
  { id: 515, name: 'Panpour', tier: 'common' },
  { id: 516, name: 'Simipour', tier: 'common' },
  { id: 517, name: 'Munna', tier: 'common' },
  { id: 518, name: 'Musharna', tier: 'common' },
  { id: 519, name: 'Pidove', tier: 'common' },
  { id: 520, name: 'Tranquill', tier: 'common' },
  { id: 521, name: 'Unfezant', tier: 'common' },
  { id: 522, name: 'Blitzle', tier: 'common' },
  { id: 523, name: 'Zebstrika', tier: 'common' },
  { id: 524, name: 'Roggenrola', tier: 'common' },
  { id: 525, name: 'Boldore', tier: 'common' },
  { id: 526, name: 'Gigalith', tier: 'common' },
  { id: 527, name: 'Woobat', tier: 'common' },
  { id: 528, name: 'Swoobat', tier: 'common' },
  { id: 529, name: 'Drilbur', tier: 'common' },
  { id: 530, name: 'Excadrill', tier: 'common' },
  { id: 531, name: 'Audino', tier: 'common' },
  { id: 532, name: 'Timburr', tier: 'common' },
  { id: 533, name: 'Gurdurr', tier: 'common' },
  { id: 534, name: 'Conkeldurr', tier: 'common' },
  { id: 535, name: 'Tympole', tier: 'common' },
  { id: 536, name: 'Palpitoad', tier: 'common' },
  { id: 537, name: 'Seismitoad', tier: 'common' },
  { id: 538, name: 'Throh', tier: 'common' },
  { id: 539, name: 'Sawk', tier: 'common' },
  { id: 540, name: 'Sewaddle', tier: 'common' },
  { id: 541, name: 'Swadloon', tier: 'common' },
  { id: 542, name: 'Leavanny', tier: 'common' },
  { id: 543, name: 'Venipede', tier: 'common' },
  { id: 544, name: 'Whirlipede', tier: 'common' },
  { id: 545, name: 'Scolipede', tier: 'common' },
  { id: 546, name: 'Cottonee', tier: 'common' },
  { id: 547, name: 'Whimsicott', tier: 'common' },
  { id: 548, name: 'Petilil', tier: 'common' },
  { id: 549, name: 'Lilligant', tier: 'common' },
  { id: 550, name: 'Basculin', tier: 'common' },
  { id: 551, name: 'Sandile', tier: 'common' },
  { id: 552, name: 'Krokorok', tier: 'common' },
  { id: 553, name: 'Krookodile', tier: 'common' },
  { id: 554, name: 'Darumaka', tier: 'common' },
  { id: 555, name: 'Darmanitan', tier: 'common' },
  { id: 556, name: 'Maractus', tier: 'common' },
  { id: 557, name: 'Dwebble', tier: 'common' },
  { id: 558, name: 'Crustle', tier: 'common' },
  { id: 559, name: 'Scraggy', tier: 'common' },
  { id: 560, name: 'Scrafty', tier: 'common' },
  { id: 561, name: 'Sigilyph', tier: 'common' },
  { id: 562, name: 'Yamask', tier: 'common' },
  { id: 563, name: 'Cofagrigus', tier: 'common' },
  { id: 564, name: 'Tirtouga', tier: 'common' },
  { id: 565, name: 'Carracosta', tier: 'common' },
  { id: 566, name: 'Archen', tier: 'common' },
  { id: 567, name: 'Archeops', tier: 'common' },
  { id: 568, name: 'Trubbish', tier: 'common' },
  { id: 569, name: 'Garbodor', tier: 'common' },
  { id: 570, name: 'Zorua', tier: 'common' },
  { id: 571, name: 'Zoroark', tier: 'common' },
  { id: 572, name: 'Minccino', tier: 'common' },
  { id: 573, name: 'Cinccino', tier: 'common' },
  { id: 574, name: 'Gothita', tier: 'common' },
  { id: 575, name: 'Gothorita', tier: 'common' },
  { id: 576, name: 'Gothitelle', tier: 'common' },
  { id: 577, name: 'Solosis', tier: 'common' },
  { id: 578, name: 'Duosion', tier: 'common' },
  { id: 579, name: 'Reuniclus', tier: 'common' },
  { id: 580, name: 'Ducklett', tier: 'common' },
  { id: 581, name: 'Swanna', tier: 'common' },
  { id: 582, name: 'Vanillite', tier: 'common' },
  { id: 583, name: 'Vanillish', tier: 'common' },
  { id: 584, name: 'Vanilluxe', tier: 'common' },
  { id: 585, name: 'Deerling', tier: 'common' },
  { id: 586, name: 'Sawsbuck', tier: 'common' },
  { id: 587, name: 'Emolga', tier: 'common' },
  { id: 588, name: 'Karrablast', tier: 'common' },
  { id: 589, name: 'Escavalier', tier: 'common' },
  { id: 590, name: 'Foongus', tier: 'common' },
  { id: 591, name: 'Amoonguss', tier: 'common' },
  { id: 592, name: 'Frillish', tier: 'common' },
  { id: 593, name: 'Jellicent', tier: 'common' },
  { id: 594, name: 'Alomomola', tier: 'common' },
  { id: 595, name: 'Joltik', tier: 'common' },
  { id: 596, name: 'Galvantula', tier: 'common' },
  { id: 597, name: 'Ferroseed', tier: 'common' },
  { id: 598, name: 'Ferrothorn', tier: 'common' },
  { id: 599, name: 'Klink', tier: 'common' },
  { id: 600, name: 'Klang', tier: 'common' },
  { id: 601, name: 'Klinklang', tier: 'common' },
  { id: 602, name: 'Tynamo', tier: 'common' },
  { id: 603, name: 'Eelektrik', tier: 'common' },
  { id: 604, name: 'Eelektross', tier: 'common' },
  { id: 605, name: 'Elgyem', tier: 'common' },
  { id: 606, name: 'Beheeyem', tier: 'common' },
  { id: 607, name: 'Litwick', tier: 'common' },
  { id: 608, name: 'Lampent', tier: 'common' },
  { id: 609, name: 'Chandelure', tier: 'common' },
  { id: 610, name: 'Axew', tier: 'common' },
  { id: 611, name: 'Fraxure', tier: 'common' },
  { id: 612, name: 'Haxorus', tier: 'common' },
  { id: 613, name: 'Cubchoo', tier: 'common' },
  { id: 614, name: 'Beartic', tier: 'common' },
  { id: 615, name: 'Cryogonal', tier: 'common' },
  { id: 616, name: 'Shelmet', tier: 'common' },
  { id: 617, name: 'Accelgor', tier: 'common' },
  { id: 618, name: 'Stunfisk', tier: 'common' },
  { id: 619, name: 'Mienfoo', tier: 'common' },
  { id: 620, name: 'Mienshao', tier: 'common' },
  { id: 621, name: 'Druddigon', tier: 'common' },
  { id: 622, name: 'Golett', tier: 'common' },
  { id: 623, name: 'Golurk', tier: 'common' },
  { id: 624, name: 'Pawniard', tier: 'common' },
  { id: 625, name: 'Bisharp', tier: 'common' },
  { id: 626, name: 'Bouffalant', tier: 'common' },
  { id: 627, name: 'Rufflet', tier: 'common' },
  { id: 628, name: 'Braviary', tier: 'common' },
  { id: 629, name: 'Vullaby', tier: 'common' },
  { id: 630, name: 'Mandibuzz', tier: 'common' },
  { id: 631, name: 'Heatmor', tier: 'common' },
  { id: 632, name: 'Durant', tier: 'common' },
  { id: 633, name: 'Deino', tier: 'common' },
  { id: 634, name: 'Zweilous', tier: 'common' },
  { id: 635, name: 'Hydreigon', tier: 'common' },
  { id: 636, name: 'Larvesta', tier: 'common' },
  { id: 637, name: 'Volcarona', tier: 'common' },
  { id: 638, name: 'Cobalion', tier: 'legendary' },
  { id: 639, name: 'Terrakion', tier: 'legendary' },
  { id: 640, name: 'Virizion', tier: 'legendary' },
  { id: 641, name: 'Tornadus', tier: 'legendary' },
  { id: 642, name: 'Thundurus', tier: 'legendary' },
  { id: 643, name: 'Reshiram', tier: 'legendary' },
  { id: 644, name: 'Zekrom', tier: 'legendary' },
  { id: 645, name: 'Landorus', tier: 'legendary' },
  { id: 646, name: 'Kyurem', tier: 'legendary' },
  { id: 647, name: 'Keldeo', tier: 'legendary' },
  { id: 648, name: 'Meloetta', tier: 'legendary' },
  { id: 649, name: 'Genesect', tier: 'legendary' },
  { id: 650, name: 'Chespin', tier: 'common' },
  { id: 651, name: 'Quilladin', tier: 'common' },
  { id: 652, name: 'Chesnaught', tier: 'common' },
  { id: 653, name: 'Fennekin', tier: 'common' },
  { id: 654, name: 'Braixen', tier: 'common' },
  { id: 655, name: 'Delphox', tier: 'common' },
  { id: 656, name: 'Froakie', tier: 'common' },
  { id: 657, name: 'Frogadier', tier: 'common' },
  { id: 658, name: 'Greninja', tier: 'common' },
  { id: 659, name: 'Bunnelby', tier: 'common' },
  { id: 660, name: 'Diggersby', tier: 'common' },
  { id: 661, name: 'Fletchling', tier: 'common' },
  { id: 662, name: 'Fletchinder', tier: 'common' },
  { id: 663, name: 'Talonflame', tier: 'common' },
  { id: 664, name: 'Scatterbug', tier: 'common' },
  { id: 665, name: 'Spewpa', tier: 'common' },
  { id: 666, name: 'Vivillon', tier: 'common' },
  { id: 667, name: 'Litleo', tier: 'common' },
  { id: 668, name: 'Pyroar', tier: 'common' },
  { id: 669, name: 'Flabebe', tier: 'common' },
  { id: 670, name: 'Floette', tier: 'common' },
  { id: 671, name: 'Florges', tier: 'common' },
  { id: 672, name: 'Skiddo', tier: 'common' },
  { id: 673, name: 'Gogoat', tier: 'common' },
  { id: 674, name: 'Pancham', tier: 'common' },
  { id: 675, name: 'Pangoro', tier: 'common' },
  { id: 676, name: 'Furfrou', tier: 'common' },
  { id: 677, name: 'Espurr', tier: 'common' },
  { id: 678, name: 'Meowstic', tier: 'common' },
  { id: 679, name: 'Honedge', tier: 'common' },
  { id: 680, name: 'Doublade', tier: 'common' },
  { id: 681, name: 'Aegislash', tier: 'common' },
  { id: 682, name: 'Spritzee', tier: 'common' },
  { id: 683, name: 'Aromatisse', tier: 'common' },
  { id: 684, name: 'Swirlix', tier: 'common' },
  { id: 685, name: 'Slurpuff', tier: 'common' },
  { id: 686, name: 'Inkay', tier: 'common' },
  { id: 687, name: 'Malamar', tier: 'common' },
  { id: 688, name: 'Binacle', tier: 'common' },
  { id: 689, name: 'Barbaracle', tier: 'common' },
  { id: 690, name: 'Skrelp', tier: 'common' },
  { id: 691, name: 'Dragalge', tier: 'common' },
  { id: 692, name: 'Clauncher', tier: 'common' },
  { id: 693, name: 'Clawitzer', tier: 'common' },
  { id: 694, name: 'Helioptile', tier: 'common' },
  { id: 695, name: 'Heliolisk', tier: 'common' },
  { id: 696, name: 'Tyrunt', tier: 'common' },
  { id: 697, name: 'Tyrantrum', tier: 'common' },
  { id: 698, name: 'Amaura', tier: 'common' },
  { id: 699, name: 'Aurorus', tier: 'common' },
  { id: 700, name: 'Sylveon', tier: 'common' },
  { id: 701, name: 'Hawlucha', tier: 'common' },
  { id: 702, name: 'Dedenne', tier: 'common' },
  { id: 703, name: 'Carbink', tier: 'common' },
  { id: 704, name: 'Goomy', tier: 'common' },
  { id: 705, name: 'Sliggoo', tier: 'common' },
  { id: 706, name: 'Goodra', tier: 'common' },
  { id: 707, name: 'Klefki', tier: 'common' },
  { id: 708, name: 'Phantump', tier: 'common' },
  { id: 709, name: 'Trevenant', tier: 'common' },
  { id: 710, name: 'Pumpkaboo', tier: 'common' },
  { id: 711, name: 'Gourgeist', tier: 'common' },
  { id: 712, name: 'Bergmite', tier: 'common' },
  { id: 713, name: 'Avalugg', tier: 'common' },
  { id: 714, name: 'Noibat', tier: 'common' },
  { id: 715, name: 'Noivern', tier: 'common' },
  { id: 716, name: 'Xerneas', tier: 'legendary' },
  { id: 717, name: 'Yveltal', tier: 'legendary' },
  { id: 718, name: 'Zygarde', tier: 'legendary' },
  { id: 719, name: 'Diancie', tier: 'legendary' },
  { id: 720, name: 'Hoopa', tier: 'legendary' },
  { id: 721, name: 'Volcanion', tier: 'legendary' },
  { id: 722, name: 'Rowlet', tier: 'common' },
  { id: 723, name: 'Dartrix', tier: 'common' },
  { id: 724, name: 'Decidueye', tier: 'common' },
  { id: 725, name: 'Litten', tier: 'common' },
  { id: 726, name: 'Torracat', tier: 'common' },
  { id: 727, name: 'Incineroar', tier: 'common' },
  { id: 728, name: 'Popplio', tier: 'common' },
  { id: 729, name: 'Brionne', tier: 'common' },
  { id: 730, name: 'Primarina', tier: 'common' },
  { id: 731, name: 'Pikipek', tier: 'common' },
  { id: 732, name: 'Trumbeak', tier: 'common' },
  { id: 733, name: 'Toucannon', tier: 'common' },
  { id: 734, name: 'Yungoos', tier: 'common' },
  { id: 735, name: 'Gumshoos', tier: 'common' },
  { id: 736, name: 'Grubbin', tier: 'common' },
  { id: 737, name: 'Charjabug', tier: 'common' },
  { id: 738, name: 'Vikavolt', tier: 'common' },
  { id: 739, name: 'Crabrawler', tier: 'common' },
  { id: 740, name: 'Crabominable', tier: 'common' },
  { id: 741, name: 'Oricorio', tier: 'common' },
  { id: 742, name: 'Cutiefly', tier: 'common' },
  { id: 743, name: 'Ribombee', tier: 'common' },
  { id: 744, name: 'Rockruff', tier: 'common' },
  { id: 745, name: 'Lycanroc', tier: 'common' },
  { id: 746, name: 'Wishiwashi', tier: 'common' },
  { id: 747, name: 'Mareanie', tier: 'common' },
  { id: 748, name: 'Toxapex', tier: 'common' },
  { id: 749, name: 'Mudbray', tier: 'common' },
  { id: 750, name: 'Mudsdale', tier: 'common' },
  { id: 751, name: 'Dewpider', tier: 'common' },
  { id: 752, name: 'Araquanid', tier: 'common' },
  { id: 753, name: 'Fomantis', tier: 'common' },
  { id: 754, name: 'Lurantis', tier: 'common' },
  { id: 755, name: 'Morelull', tier: 'common' },
  { id: 756, name: 'Shiinotic', tier: 'common' },
  { id: 757, name: 'Salandit', tier: 'common' },
  { id: 758, name: 'Salazzle', tier: 'common' },
  { id: 759, name: 'Stufful', tier: 'common' },
  { id: 760, name: 'Bewear', tier: 'common' },
  { id: 761, name: 'Bounsweet', tier: 'common' },
  { id: 762, name: 'Steenee', tier: 'common' },
  { id: 763, name: 'Tsareena', tier: 'common' },
  { id: 764, name: 'Comfey', tier: 'common' },
  { id: 765, name: 'Oranguru', tier: 'common' },
  { id: 766, name: 'Passimian', tier: 'common' },
  { id: 767, name: 'Wimpod', tier: 'common' },
  { id: 768, name: 'Golisopod', tier: 'common' },
  { id: 769, name: 'Sandygast', tier: 'common' },
  { id: 770, name: 'Palossand', tier: 'common' },
  { id: 771, name: 'Pyukumuku', tier: 'common' },
  { id: 772, name: 'Type Null', tier: 'legendary' },
  { id: 773, name: 'Silvally', tier: 'legendary' },
  { id: 774, name: 'Minior', tier: 'common' },
  { id: 775, name: 'Komala', tier: 'common' },
  { id: 776, name: 'Turtonator', tier: 'common' },
  { id: 777, name: 'Togedemaru', tier: 'common' },
  { id: 778, name: 'Mimikyu', tier: 'common' },
  { id: 779, name: 'Bruxish', tier: 'common' },
  { id: 780, name: 'Drampa', tier: 'common' },
  { id: 781, name: 'Dhelmise', tier: 'common' },
  { id: 782, name: 'Jangmo-o', tier: 'common' },
  { id: 783, name: 'Hakamo-o', tier: 'common' },
  { id: 784, name: 'Kommo-o', tier: 'common' },
  { id: 785, name: 'Tapu Koko', tier: 'legendary' },
  { id: 786, name: 'Tapu Lele', tier: 'legendary' },
  { id: 787, name: 'Tapu Bulu', tier: 'legendary' },
  { id: 788, name: 'Tapu Fini', tier: 'legendary' },
  { id: 789, name: 'Cosmog', tier: 'legendary' },
  { id: 790, name: 'Cosmoem', tier: 'legendary' },
  { id: 791, name: 'Solgaleo', tier: 'legendary' },
  { id: 792, name: 'Lunala', tier: 'legendary' },
  { id: 793, name: 'Nihilego', tier: 'common' },
  { id: 794, name: 'Buzzwole', tier: 'common' },
  { id: 795, name: 'Pheromosa', tier: 'common' },
  { id: 796, name: 'Xurkitree', tier: 'common' },
  { id: 797, name: 'Celesteela', tier: 'common' },
  { id: 798, name: 'Kartana', tier: 'common' },
  { id: 799, name: 'Guzzlord', tier: 'common' },
  { id: 800, name: 'Necrozma', tier: 'legendary' },
  { id: 801, name: 'Magearna', tier: 'legendary' },
  { id: 802, name: 'Marshadow', tier: 'legendary' },
  { id: 803, name: 'Poipole', tier: 'common' },
  { id: 804, name: 'Naganadel', tier: 'common' },
  { id: 805, name: 'Stakataka', tier: 'common' },
  { id: 806, name: 'Blacephalon', tier: 'common' },
  { id: 807, name: 'Zeraora', tier: 'legendary' },
  { id: 808, name: 'Meltan', tier: 'legendary' },
  { id: 809, name: 'Melmetal', tier: 'legendary' },
  { id: 810, name: 'Grookey', tier: 'common' },
  { id: 811, name: 'Thwackey', tier: 'common' },
  { id: 812, name: 'Rillaboom', tier: 'common' },
  { id: 813, name: 'Scorbunny', tier: 'common' },
  { id: 814, name: 'Raboot', tier: 'common' },
  { id: 815, name: 'Cinderace', tier: 'common' },
  { id: 816, name: 'Sobble', tier: 'common' },
  { id: 817, name: 'Drizzile', tier: 'common' },
  { id: 818, name: 'Inteleon', tier: 'common' },
  { id: 819, name: 'Skwovet', tier: 'common' },
  { id: 820, name: 'Greedent', tier: 'common' },
  { id: 821, name: 'Rookidee', tier: 'common' },
  { id: 822, name: 'Corvisquire', tier: 'common' },
  { id: 823, name: 'Corviknight', tier: 'common' },
  { id: 824, name: 'Blipbug', tier: 'common' },
  { id: 825, name: 'Dottler', tier: 'common' },
  { id: 826, name: 'Orbeetle', tier: 'common' },
  { id: 827, name: 'Nickit', tier: 'common' },
  { id: 828, name: 'Thievul', tier: 'common' },
  { id: 829, name: 'Gossifleur', tier: 'common' },
  { id: 830, name: 'Eldegoss', tier: 'common' },
  { id: 831, name: 'Wooloo', tier: 'common' },
  { id: 832, name: 'Dubwool', tier: 'common' },
  { id: 833, name: 'Chewtle', tier: 'common' },
  { id: 834, name: 'Drednaw', tier: 'common' },
  { id: 835, name: 'Yamper', tier: 'common' },
  { id: 836, name: 'Boltund', tier: 'common' },
  { id: 837, name: 'Rolycoly', tier: 'common' },
  { id: 838, name: 'Carkol', tier: 'common' },
  { id: 839, name: 'Coalossal', tier: 'common' },
  { id: 840, name: 'Applin', tier: 'common' },
  { id: 841, name: 'Flapple', tier: 'common' },
  { id: 842, name: 'Appletun', tier: 'common' },
  { id: 843, name: 'Silicobra', tier: 'common' },
  { id: 844, name: 'Sandaconda', tier: 'common' },
  { id: 845, name: 'Cramorant', tier: 'common' },
  { id: 846, name: 'Arrokuda', tier: 'common' },
  { id: 847, name: 'Barraskewda', tier: 'common' },
  { id: 848, name: 'Toxel', tier: 'common' },
  { id: 849, name: 'Toxtricity', tier: 'common' },
  { id: 850, name: 'Sizzlipede', tier: 'common' },
  { id: 851, name: 'Centiskorch', tier: 'common' },
  { id: 852, name: 'Clobbopus', tier: 'common' },
  { id: 853, name: 'Grapploct', tier: 'common' },
  { id: 854, name: 'Sinistea', tier: 'common' },
  { id: 855, name: 'Polteageist', tier: 'common' },
  { id: 856, name: 'Hatenna', tier: 'common' },
  { id: 857, name: 'Hattrem', tier: 'common' },
  { id: 858, name: 'Hatterene', tier: 'common' },
  { id: 859, name: 'Impidimp', tier: 'common' },
  { id: 860, name: 'Morgrem', tier: 'common' },
  { id: 861, name: 'Grimmsnarl', tier: 'common' },
  { id: 862, name: 'Obstagoon', tier: 'common' },
  { id: 863, name: 'Perrserker', tier: 'common' },
  { id: 864, name: 'Cursola', tier: 'common' },
  { id: 865, name: 'Sirfetchd', tier: 'common' },
  { id: 866, name: 'Mr. Rime', tier: 'common' },
  { id: 867, name: 'Runerigus', tier: 'common' },
  { id: 868, name: 'Milcery', tier: 'common' },
  { id: 869, name: 'Alcremie', tier: 'common' },
  { id: 870, name: 'Falinks', tier: 'common' },
  { id: 871, name: 'Pincurchin', tier: 'common' },
  { id: 872, name: 'Snom', tier: 'common' },
  { id: 873, name: 'Frosmoth', tier: 'common' },
  { id: 874, name: 'Stonjourner', tier: 'common' },
  { id: 875, name: 'Eiscue', tier: 'common' },
  { id: 876, name: 'Indeedee', tier: 'common' },
  { id: 877, name: 'Morpeko', tier: 'common' },
  { id: 878, name: 'Cufant', tier: 'common' },
  { id: 879, name: 'Copperajah', tier: 'common' },
  { id: 880, name: 'Dracozolt', tier: 'common' },
  { id: 881, name: 'Arctozolt', tier: 'common' },
  { id: 882, name: 'Dracovish', tier: 'common' },
  { id: 883, name: 'Arctovish', tier: 'common' },
  { id: 884, name: 'Duraludon', tier: 'common' },
  { id: 885, name: 'Dreepy', tier: 'common' },
  { id: 886, name: 'Drakloak', tier: 'common' },
  { id: 887, name: 'Dragapult', tier: 'common' },
  { id: 888, name: 'Zacian', tier: 'legendary' },
  { id: 889, name: 'Zamazenta', tier: 'legendary' },
  { id: 890, name: 'Eternatus', tier: 'legendary' },
  { id: 891, name: 'Kubfu', tier: 'legendary' },
  { id: 892, name: 'Urshifu', tier: 'legendary' },
  { id: 893, name: 'Zarude', tier: 'legendary' },
  { id: 894, name: 'Regieleki', tier: 'legendary' },
  { id: 895, name: 'Regidrago', tier: 'legendary' },
  { id: 896, name: 'Glastrier', tier: 'legendary' },
  { id: 897, name: 'Spectrier', tier: 'legendary' },
  { id: 898, name: 'Calyrex', tier: 'legendary' },
  { id: 899, name: 'Wyrdeer', tier: 'common' },
  { id: 900, name: 'Kleavor', tier: 'common' },
  { id: 901, name: 'Ursaluna', tier: 'common' },
  { id: 902, name: 'Basculegion', tier: 'common' },
  { id: 903, name: 'Sneasler', tier: 'common' },
  { id: 904, name: 'Overqwil', tier: 'common' },
  { id: 905, name: 'Enamorus', tier: 'legendary' },
  { id: 906, name: 'Sprigatito', tier: 'common' },
  { id: 907, name: 'Floragato', tier: 'common' },
  { id: 908, name: 'Meowscarada', tier: 'common' },
  { id: 909, name: 'Fuecoco', tier: 'common' },
  { id: 910, name: 'Crocalor', tier: 'common' },
  { id: 911, name: 'Skeledirge', tier: 'common' },
  { id: 912, name: 'Quaxly', tier: 'common' },
  { id: 913, name: 'Quaxwell', tier: 'common' },
  { id: 914, name: 'Quaquaval', tier: 'common' },
  { id: 915, name: 'Lechonk', tier: 'common' },
  { id: 916, name: 'Oinkologne', tier: 'common' },
  { id: 917, name: 'Tarountula', tier: 'common' },
  { id: 918, name: 'Spidops', tier: 'common' },
  { id: 919, name: 'Nymble', tier: 'common' },
  { id: 920, name: 'Lokix', tier: 'common' },
  { id: 921, name: 'Pawmi', tier: 'common' },
  { id: 922, name: 'Pawmo', tier: 'common' },
  { id: 923, name: 'Pawmot', tier: 'common' },
  { id: 924, name: 'Tandemaus', tier: 'common' },
  { id: 925, name: 'Maushold', tier: 'common' },
  { id: 926, name: 'Fidough', tier: 'common' },
  { id: 927, name: 'Dachsbun', tier: 'common' },
  { id: 928, name: 'Smoliv', tier: 'common' },
  { id: 929, name: 'Dolliv', tier: 'common' },
  { id: 930, name: 'Arboliva', tier: 'common' },
  { id: 931, name: 'Squawkabilly', tier: 'common' },
  { id: 932, name: 'Nacli', tier: 'common' },
  { id: 933, name: 'Naclstack', tier: 'common' },
  { id: 934, name: 'Garganacl', tier: 'common' },
  { id: 935, name: 'Charcadet', tier: 'common' },
  { id: 936, name: 'Armarouge', tier: 'common' },
  { id: 937, name: 'Ceruledge', tier: 'common' },
  { id: 938, name: 'Tadbulb', tier: 'common' },
  { id: 939, name: 'Bellibolt', tier: 'common' },
  { id: 940, name: 'Wattrel', tier: 'common' },
  { id: 941, name: 'Kilowattrel', tier: 'common' },
  { id: 942, name: 'Maschiff', tier: 'common' },
  { id: 943, name: 'Mabosstiff', tier: 'common' },
  { id: 944, name: 'Shroodle', tier: 'common' },
  { id: 945, name: 'Grafaiai', tier: 'common' },
  { id: 946, name: 'Bramblin', tier: 'common' },
  { id: 947, name: 'Brambleghast', tier: 'common' },
  { id: 948, name: 'Toedscool', tier: 'common' },
  { id: 949, name: 'Toedscruel', tier: 'common' },
  { id: 950, name: 'Klawf', tier: 'common' },
  { id: 951, name: 'Capsakid', tier: 'common' },
  { id: 952, name: 'Scovillain', tier: 'common' },
  { id: 953, name: 'Rellor', tier: 'common' },
  { id: 954, name: 'Rabsca', tier: 'common' },
  { id: 955, name: 'Flittle', tier: 'common' },
  { id: 956, name: 'Espathra', tier: 'common' },
  { id: 957, name: 'Tinkatink', tier: 'common' },
  { id: 958, name: 'Tinkatuff', tier: 'common' },
  { id: 959, name: 'Tinkaton', tier: 'common' },
  { id: 960, name: 'Wiglett', tier: 'common' },
  { id: 961, name: 'Wugtrio', tier: 'common' },
  { id: 962, name: 'Bombirdier', tier: 'common' },
  { id: 963, name: 'Finizen', tier: 'common' },
  { id: 964, name: 'Palafin', tier: 'common' },
  { id: 965, name: 'Varoom', tier: 'common' },
  { id: 966, name: 'Revavroom', tier: 'common' },
  { id: 967, name: 'Cyclizar', tier: 'common' },
  { id: 968, name: 'Orthworm', tier: 'common' },
  { id: 969, name: 'Glimmet', tier: 'common' },
  { id: 970, name: 'Glimmora', tier: 'common' },
  { id: 971, name: 'Greavard', tier: 'common' },
  { id: 972, name: 'Houndstone', tier: 'common' },
  { id: 973, name: 'Flamigo', tier: 'common' },
  { id: 974, name: 'Cetoddle', tier: 'common' },
  { id: 975, name: 'Cetitan', tier: 'common' },
  { id: 976, name: 'Veluza', tier: 'common' },
  { id: 977, name: 'Dondozo', tier: 'common' },
  { id: 978, name: 'Tatsugiri', tier: 'common' },
  { id: 979, name: 'Annihilape', tier: 'common' },
  { id: 980, name: 'Clodsire', tier: 'common' },
  { id: 981, name: 'Farigiraf', tier: 'common' },
  { id: 982, name: 'Dudunsparce', tier: 'common' },
  { id: 983, name: 'Kingambit', tier: 'common' },
  { id: 984, name: 'Great Tusk', tier: 'common' },
  { id: 985, name: 'Scream Tail', tier: 'common' },
  { id: 986, name: 'Brute Bonnet', tier: 'common' },
  { id: 987, name: 'Flutter Mane', tier: 'common' },
  { id: 988, name: 'Slither Wing', tier: 'common' },
  { id: 989, name: 'Sandy Shocks', tier: 'common' },
  { id: 990, name: 'Iron Treads', tier: 'common' },
  { id: 991, name: 'Iron Bundle', tier: 'common' },
  { id: 992, name: 'Iron Hands', tier: 'common' },
  { id: 993, name: 'Iron Jugulis', tier: 'common' },
  { id: 994, name: 'Iron Moth', tier: 'common' },
  { id: 995, name: 'Iron Thorns', tier: 'common' },
  { id: 996, name: 'Frigibax', tier: 'common' },
  { id: 997, name: 'Arctibax', tier: 'common' },
  { id: 998, name: 'Baxcalibur', tier: 'common' },
  { id: 999, name: 'Gimmighoul', tier: 'common' },
  { id: 1000, name: 'Gholdengo', tier: 'common' },
  { id: 1001, name: 'Wo-Chien', tier: 'legendary' },
  { id: 1002, name: 'Chien-Pao', tier: 'legendary' },
  { id: 1003, name: 'Ting-Lu', tier: 'legendary' },
  { id: 1004, name: 'Chi-Yu', tier: 'legendary' },
  { id: 1005, name: 'Roaring Moon', tier: 'common' },
  { id: 1006, name: 'Iron Valiant', tier: 'common' },
  { id: 1007, name: 'Koraidon', tier: 'legendary' },
  { id: 1008, name: 'Miraidon', tier: 'legendary' },
  { id: 1009, name: 'Walking Wake', tier: 'common' },
  { id: 1010, name: 'Iron Leaves', tier: 'common' },
  { id: 1011, name: 'Dipplin', tier: 'common' },
  { id: 1012, name: 'Poltchageist', tier: 'common' },
  { id: 1013, name: 'Sinistcha', tier: 'common' },
  { id: 1014, name: 'Okidogi', tier: 'legendary' },
  { id: 1015, name: 'Munkidori', tier: 'legendary' },
  { id: 1016, name: 'Fezandipiti', tier: 'legendary' },
  { id: 1017, name: 'Ogerpon', tier: 'legendary' },
  { id: 1018, name: 'Archaludon', tier: 'common' },
  { id: 1019, name: 'Hydrapple', tier: 'common' },
  { id: 1020, name: 'Gouging Fire', tier: 'common' },
  { id: 1021, name: 'Raging Bolt', tier: 'common' },
  { id: 1022, name: 'Iron Boulder', tier: 'common' },
  { id: 1023, name: 'Iron Crown', tier: 'common' },
  { id: 1024, name: 'Terapagos', tier: 'legendary' },
  { id: 1025, name: 'Pecharunt', tier: 'legendary' }
];

/* official artwork (all gens) */
const POKE_ART = (id) => `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/${id}.png`;

/* animated sprite for the wandering companion:
   Gen 1-5 → BW animated set; Gen 6-9 → Showdown animated set */
const POKE_ANI = (id) => id <= 649
  ? `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/${id}.gif`
  : `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/${id}.gif`;

/* bundled audio */
const POKE_CRY   = (id) => `cries/${id}.mp3`;    /* official game cry */
const POKE_VOICE = (id) => `voices/${id}.m4a`;   /* generated "says its name" */
const POKE_CHIRP = (id) => `chirps/${id}.m4a`;   /* short ambient "Pika pika!" */

/* full evolution map: id → next form id (arrays = branching, e.g. Eevee) */
const EVOLVES = {
  1: 2,
  2: 3,
  4: 5,
  5: 6,
  7: 8,
  8: 9,
  10: 11,
  11: 12,
  13: 14,
  14: 15,
  16: 17,
  17: 18,
  19: 20,
  21: 22,
  23: 24,
  25: 26,
  27: 28,
  29: 30,
  30: 31,
  32: 33,
  33: 34,
  35: 36,
  37: 38,
  39: 40,
  41: 42,
  42: 169,
  43: 44,
  44: [45, 182],
  46: 47,
  48: 49,
  50: 51,
  52: [53, 863],
  54: 55,
  56: 57,
  57: 979,
  58: 59,
  60: 61,
  61: [62, 186],
  63: 64,
  64: 65,
  66: 67,
  67: 68,
  69: 70,
  70: 71,
  72: 73,
  74: 75,
  75: 76,
  77: 78,
  79: [80, 199],
  81: 82,
  82: 462,
  83: 865,
  84: 85,
  86: 87,
  88: 89,
  90: 91,
  92: 93,
  93: 94,
  95: 208,
  96: 97,
  98: 99,
  100: 101,
  102: 103,
  104: 105,
  108: 463,
  109: 110,
  111: 112,
  112: 464,
  113: 242,
  114: 465,
  116: 117,
  117: 230,
  118: 119,
  120: 121,
  122: 866,
  123: [212, 900],
  125: 466,
  126: 467,
  129: 130,
  133: [134, 135, 136, 196, 197, 470, 471, 700],
  137: 233,
  138: 139,
  140: 141,
  147: 148,
  148: 149,
  152: 153,
  153: 154,
  155: 156,
  156: 157,
  158: 159,
  159: 160,
  161: 162,
  163: 164,
  165: 166,
  167: 168,
  170: 171,
  172: 25,
  173: 35,
  174: 39,
  175: 176,
  176: 468,
  177: 178,
  179: 180,
  180: 181,
  183: 184,
  187: 188,
  188: 189,
  190: 424,
  191: 192,
  193: 469,
  194: [195, 980],
  198: 430,
  200: 429,
  203: 981,
  204: 205,
  206: 982,
  207: 472,
  209: 210,
  211: 904,
  215: [461, 903],
  216: 217,
  217: 901,
  218: 219,
  220: 221,
  221: 473,
  222: 864,
  223: 224,
  228: 229,
  231: 232,
  233: 474,
  234: 899,
  236: [106, 107, 237],
  238: 124,
  239: 125,
  240: 126,
  246: 247,
  247: 248,
  252: 253,
  253: 254,
  255: 256,
  256: 257,
  258: 259,
  259: 260,
  261: 262,
  263: 264,
  264: 862,
  265: [266, 268],
  266: 267,
  268: 269,
  270: 271,
  271: 272,
  273: 274,
  274: 275,
  276: 277,
  278: 279,
  280: 281,
  281: [282, 475],
  283: 284,
  285: 286,
  287: 288,
  288: 289,
  290: [291, 292],
  293: 294,
  294: 295,
  296: 297,
  298: 183,
  299: 476,
  300: 301,
  304: 305,
  305: 306,
  307: 308,
  309: 310,
  315: 407,
  316: 317,
  318: 319,
  320: 321,
  322: 323,
  325: 326,
  328: 329,
  329: 330,
  331: 332,
  333: 334,
  339: 340,
  341: 342,
  343: 344,
  345: 346,
  347: 348,
  349: 350,
  353: 354,
  355: 356,
  356: 477,
  360: 202,
  361: [362, 478],
  363: 364,
  364: 365,
  366: [367, 368],
  371: 372,
  372: 373,
  374: 375,
  375: 376,
  387: 388,
  388: 389,
  390: 391,
  391: 392,
  393: 394,
  394: 395,
  396: 397,
  397: 398,
  399: 400,
  401: 402,
  403: 404,
  404: 405,
  406: 315,
  408: 409,
  410: 411,
  412: [413, 414],
  415: 416,
  418: 419,
  420: 421,
  422: 423,
  425: 426,
  427: 428,
  431: 432,
  433: 358,
  434: 435,
  436: 437,
  438: 185,
  439: 122,
  440: 113,
  443: 444,
  444: 445,
  446: 143,
  447: 448,
  449: 450,
  451: 452,
  453: 454,
  456: 457,
  458: 226,
  459: 460,
  489: 490,
  495: 496,
  496: 497,
  498: 499,
  499: 500,
  501: 502,
  502: 503,
  504: 505,
  506: 507,
  507: 508,
  509: 510,
  511: 512,
  513: 514,
  515: 516,
  517: 518,
  519: 520,
  520: 521,
  522: 523,
  524: 525,
  525: 526,
  527: 528,
  529: 530,
  532: 533,
  533: 534,
  535: 536,
  536: 537,
  540: 541,
  541: 542,
  543: 544,
  544: 545,
  546: 547,
  548: 549,
  550: 902,
  551: 552,
  552: 553,
  554: 555,
  557: 558,
  559: 560,
  562: [563, 867],
  564: 565,
  566: 567,
  568: 569,
  570: 571,
  572: 573,
  574: 575,
  575: 576,
  577: 578,
  578: 579,
  580: 581,
  582: 583,
  583: 584,
  585: 586,
  588: 589,
  590: 591,
  592: 593,
  595: 596,
  597: 598,
  599: 600,
  600: 601,
  602: 603,
  603: 604,
  605: 606,
  607: 608,
  608: 609,
  610: 611,
  611: 612,
  613: 614,
  616: 617,
  619: 620,
  622: 623,
  624: 625,
  625: 983,
  627: 628,
  629: 630,
  633: 634,
  634: 635,
  636: 637,
  650: 651,
  651: 652,
  653: 654,
  654: 655,
  656: 657,
  657: 658,
  659: 660,
  661: 662,
  662: 663,
  664: 665,
  665: 666,
  667: 668,
  669: 670,
  670: 671,
  672: 673,
  674: 675,
  677: 678,
  679: 680,
  680: 681,
  682: 683,
  684: 685,
  686: 687,
  688: 689,
  690: 691,
  692: 693,
  694: 695,
  696: 697,
  698: 699,
  704: 705,
  705: 706,
  708: 709,
  710: 711,
  712: 713,
  714: 715,
  722: 723,
  723: 724,
  725: 726,
  726: 727,
  728: 729,
  729: 730,
  731: 732,
  732: 733,
  734: 735,
  736: 737,
  737: 738,
  739: 740,
  742: 743,
  744: 745,
  747: 748,
  749: 750,
  751: 752,
  753: 754,
  755: 756,
  757: 758,
  759: 760,
  761: 762,
  762: 763,
  767: 768,
  769: 770,
  772: 773,
  782: 783,
  783: 784,
  789: 790,
  790: [791, 792],
  803: 804,
  810: 811,
  811: 812,
  813: 814,
  814: 815,
  816: 817,
  817: 818,
  819: 820,
  821: 822,
  822: 823,
  824: 825,
  825: 826,
  827: 828,
  829: 830,
  831: 832,
  833: 834,
  835: 836,
  837: 838,
  838: 839,
  840: [841, 842, 1011],
  843: 844,
  846: 847,
  848: 849,
  850: 851,
  852: 853,
  854: 855,
  856: 857,
  857: 858,
  859: 860,
  860: 861,
  868: 869,
  872: 873,
  878: 879,
  884: 1018,
  885: 886,
  886: 887,
  891: 892,
  906: 907,
  907: 908,
  909: 910,
  910: 911,
  912: 913,
  913: 914,
  915: 916,
  917: 918,
  919: 920,
  921: 922,
  922: 923,
  924: 925,
  926: 927,
  928: 929,
  929: 930,
  932: 933,
  933: 934,
  935: [936, 937],
  938: 939,
  940: 941,
  942: 943,
  944: 945,
  946: 947,
  948: 949,
  951: 952,
  953: 954,
  955: 956,
  957: 958,
  958: 959,
  960: 961,
  963: 964,
  965: 966,
  969: 970,
  971: 972,
  974: 975,
  996: 997,
  997: 998,
  999: 1000,
  1011: 1019,
  1012: 1013
};

/* care items: emoji, name, hearts gained */
const CARE_ITEMS = {
  berry: { emoji: '🍎', name: 'berry', hearts: 1 },
  toy:   { emoji: '🎾', name: 'toy',   hearts: 2 },
  gift:  { emoji: '🎁', name: 'gift',  hearts: 3 }
};
