/* Gen-1 Pokémon roster for the reward system (names via PokéAPI).
   Artwork is hot-linked at runtime from the PokeAPI sprites mirror —
   personal / educational fan use only. */
const POKEMON = [
  { id: 1, name: 'Bulbasaur', tier: 'common' },
  { id: 2, name: 'Ivysaur', tier: 'common' },
  { id: 3, name: 'Venusaur', tier: 'rare' },
  { id: 4, name: 'Charmander', tier: 'common' },
  { id: 5, name: 'Charmeleon', tier: 'common' },
  { id: 6, name: 'Charizard', tier: 'rare' },
  { id: 7, name: 'Squirtle', tier: 'common' },
  { id: 8, name: 'Wartortle', tier: 'common' },
  { id: 9, name: 'Blastoise', tier: 'rare' },
  { id: 10, name: 'Caterpie', tier: 'common' },
  { id: 11, name: 'Metapod', tier: 'common' },
  { id: 12, name: 'Butterfree', tier: 'common' },
  { id: 13, name: 'Weedle', tier: 'common' },
  { id: 14, name: 'Kakuna', tier: 'common' },
  { id: 15, name: 'Beedrill', tier: 'common' },
  { id: 16, name: 'Pidgey', tier: 'common' },
  { id: 17, name: 'Pidgeotto', tier: 'common' },
  { id: 18, name: 'Pidgeot', tier: 'common' },
  { id: 19, name: 'Rattata', tier: 'common' },
  { id: 20, name: 'Raticate', tier: 'common' },
  { id: 21, name: 'Spearow', tier: 'common' },
  { id: 22, name: 'Fearow', tier: 'common' },
  { id: 23, name: 'Ekans', tier: 'common' },
  { id: 24, name: 'Arbok', tier: 'common' },
  { id: 25, name: 'Pikachu', tier: 'common' },
  { id: 26, name: 'Raichu', tier: 'common' },
  { id: 27, name: 'Sandshrew', tier: 'common' },
  { id: 28, name: 'Sandslash', tier: 'common' },
  { id: 29, name: 'Nidoran F', tier: 'common' },
  { id: 30, name: 'Nidorina', tier: 'common' },
  { id: 31, name: 'Nidoqueen', tier: 'common' },
  { id: 32, name: 'Nidoran M', tier: 'common' },
  { id: 33, name: 'Nidorino', tier: 'common' },
  { id: 34, name: 'Nidoking', tier: 'common' },
  { id: 35, name: 'Clefairy', tier: 'common' },
  { id: 36, name: 'Clefable', tier: 'common' },
  { id: 37, name: 'Vulpix', tier: 'common' },
  { id: 38, name: 'Ninetales', tier: 'common' },
  { id: 39, name: 'Jigglypuff', tier: 'common' },
  { id: 40, name: 'Wigglytuff', tier: 'common' },
  { id: 41, name: 'Zubat', tier: 'common' },
  { id: 42, name: 'Golbat', tier: 'common' },
  { id: 43, name: 'Oddish', tier: 'common' },
  { id: 44, name: 'Gloom', tier: 'common' },
  { id: 45, name: 'Vileplume', tier: 'common' },
  { id: 46, name: 'Paras', tier: 'common' },
  { id: 47, name: 'Parasect', tier: 'common' },
  { id: 48, name: 'Venonat', tier: 'common' },
  { id: 49, name: 'Venomoth', tier: 'common' },
  { id: 50, name: 'Diglett', tier: 'common' },
  { id: 51, name: 'Dugtrio', tier: 'common' },
  { id: 52, name: 'Meowth', tier: 'common' },
  { id: 53, name: 'Persian', tier: 'common' },
  { id: 54, name: 'Psyduck', tier: 'common' },
  { id: 55, name: 'Golduck', tier: 'common' },
  { id: 56, name: 'Mankey', tier: 'common' },
  { id: 57, name: 'Primeape', tier: 'common' },
  { id: 58, name: 'Growlithe', tier: 'common' },
  { id: 59, name: 'Arcanine', tier: 'rare' },
  { id: 60, name: 'Poliwag', tier: 'common' },
  { id: 61, name: 'Poliwhirl', tier: 'common' },
  { id: 62, name: 'Poliwrath', tier: 'common' },
  { id: 63, name: 'Abra', tier: 'common' },
  { id: 64, name: 'Kadabra', tier: 'common' },
  { id: 65, name: 'Alakazam', tier: 'rare' },
  { id: 66, name: 'Machop', tier: 'common' },
  { id: 67, name: 'Machoke', tier: 'common' },
  { id: 68, name: 'Machamp', tier: 'rare' },
  { id: 69, name: 'Bellsprout', tier: 'common' },
  { id: 70, name: 'Weepinbell', tier: 'common' },
  { id: 71, name: 'Victreebel', tier: 'common' },
  { id: 72, name: 'Tentacool', tier: 'common' },
  { id: 73, name: 'Tentacruel', tier: 'common' },
  { id: 74, name: 'Geodude', tier: 'common' },
  { id: 75, name: 'Graveler', tier: 'common' },
  { id: 76, name: 'Golem', tier: 'rare' },
  { id: 77, name: 'Ponyta', tier: 'common' },
  { id: 78, name: 'Rapidash', tier: 'common' },
  { id: 79, name: 'Slowpoke', tier: 'common' },
  { id: 80, name: 'Slowbro', tier: 'common' },
  { id: 81, name: 'Magnemite', tier: 'common' },
  { id: 82, name: 'Magneton', tier: 'common' },
  { id: 83, name: 'Farfetchd', tier: 'common' },
  { id: 84, name: 'Doduo', tier: 'common' },
  { id: 85, name: 'Dodrio', tier: 'common' },
  { id: 86, name: 'Seel', tier: 'common' },
  { id: 87, name: 'Dewgong', tier: 'common' },
  { id: 88, name: 'Grimer', tier: 'common' },
  { id: 89, name: 'Muk', tier: 'common' },
  { id: 90, name: 'Shellder', tier: 'common' },
  { id: 91, name: 'Cloyster', tier: 'common' },
  { id: 92, name: 'Gastly', tier: 'common' },
  { id: 93, name: 'Haunter', tier: 'common' },
  { id: 94, name: 'Gengar', tier: 'rare' },
  { id: 95, name: 'Onix', tier: 'common' },
  { id: 96, name: 'Drowzee', tier: 'common' },
  { id: 97, name: 'Hypno', tier: 'common' },
  { id: 98, name: 'Krabby', tier: 'common' },
  { id: 99, name: 'Kingler', tier: 'common' },
  { id: 100, name: 'Voltorb', tier: 'common' },
  { id: 101, name: 'Electrode', tier: 'common' },
  { id: 102, name: 'Exeggcute', tier: 'common' },
  { id: 103, name: 'Exeggutor', tier: 'common' },
  { id: 104, name: 'Cubone', tier: 'common' },
  { id: 105, name: 'Marowak', tier: 'common' },
  { id: 106, name: 'Hitmonlee', tier: 'common' },
  { id: 107, name: 'Hitmonchan', tier: 'common' },
  { id: 108, name: 'Lickitung', tier: 'common' },
  { id: 109, name: 'Koffing', tier: 'common' },
  { id: 110, name: 'Weezing', tier: 'common' },
  { id: 111, name: 'Rhyhorn', tier: 'common' },
  { id: 112, name: 'Rhydon', tier: 'rare' },
  { id: 113, name: 'Chansey', tier: 'common' },
  { id: 114, name: 'Tangela', tier: 'common' },
  { id: 115, name: 'Kangaskhan', tier: 'common' },
  { id: 116, name: 'Horsea', tier: 'common' },
  { id: 117, name: 'Seadra', tier: 'common' },
  { id: 118, name: 'Goldeen', tier: 'common' },
  { id: 119, name: 'Seaking', tier: 'common' },
  { id: 120, name: 'Staryu', tier: 'common' },
  { id: 121, name: 'Starmie', tier: 'common' },
  { id: 122, name: 'Mr. Mime', tier: 'common' },
  { id: 123, name: 'Scyther', tier: 'common' },
  { id: 124, name: 'Jynx', tier: 'common' },
  { id: 125, name: 'Electabuzz', tier: 'common' },
  { id: 126, name: 'Magmar', tier: 'common' },
  { id: 127, name: 'Pinsir', tier: 'common' },
  { id: 128, name: 'Tauros', tier: 'common' },
  { id: 129, name: 'Magikarp', tier: 'common' },
  { id: 130, name: 'Gyarados', tier: 'rare' },
  { id: 131, name: 'Lapras', tier: 'rare' },
  { id: 132, name: 'Ditto', tier: 'common' },
  { id: 133, name: 'Eevee', tier: 'common' },
  { id: 134, name: 'Vaporeon', tier: 'rare' },
  { id: 135, name: 'Jolteon', tier: 'rare' },
  { id: 136, name: 'Flareon', tier: 'rare' },
  { id: 137, name: 'Porygon', tier: 'common' },
  { id: 138, name: 'Omanyte', tier: 'common' },
  { id: 139, name: 'Omastar', tier: 'common' },
  { id: 140, name: 'Kabuto', tier: 'common' },
  { id: 141, name: 'Kabutops', tier: 'common' },
  { id: 142, name: 'Aerodactyl', tier: 'rare' },
  { id: 143, name: 'Snorlax', tier: 'rare' },
  { id: 144, name: 'Articuno', tier: 'legendary' },
  { id: 145, name: 'Zapdos', tier: 'legendary' },
  { id: 146, name: 'Moltres', tier: 'legendary' },
  { id: 147, name: 'Dratini', tier: 'common' },
  { id: 148, name: 'Dragonair', tier: 'common' },
  { id: 149, name: 'Dragonite', tier: 'rare' },
  { id: 150, name: 'Mewtwo', tier: 'legendary' },
  { id: 151, name: 'Mew', tier: 'legendary' }
];
const POKE_ART = (id) => `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/${id}.png`;

/* Gen-1 evolution chains (id → next form; Eevee branches randomly).
   Used by the Pokémon-pal feature: friendship level 3 evolves a base form,
   level 6 evolves a middle form. */
const EVOLVES = {
  1:2, 2:3, 4:5, 5:6, 7:8, 8:9, 10:11, 11:12, 13:14, 14:15, 16:17, 17:18,
  19:20, 21:22, 23:24, 25:26, 27:28, 29:30, 30:31, 32:33, 33:34, 35:36,
  37:38, 39:40, 41:42, 43:44, 44:45, 46:47, 48:49, 50:51, 52:53, 54:55,
  56:57, 58:59, 60:61, 61:62, 63:64, 64:65, 66:67, 67:68, 69:70, 70:71,
  72:73, 74:75, 75:76, 77:78, 79:80, 81:82, 84:85, 86:87, 88:89, 90:91,
  92:93, 93:94, 96:97, 98:99, 100:101, 102:103, 104:105, 109:110, 111:112,
  116:117, 118:119, 120:121, 129:130, 133:[134,135,136], 138:139, 140:141,
  147:148, 148:149
};

/* care items: emoji, name, hearts gained */
const CARE_ITEMS = {
  berry: { emoji: '🍎', name: 'berry', hearts: 1 },
  toy:   { emoji: '🎾', name: 'toy',   hearts: 2 },
  gift:  { emoji: '🎁', name: 'gift',  hearts: 3 }
};

/* animated pixel sprite (Gen-5 battle idle animation) — the wandering companion */
const POKE_ANI = (id) => `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/${id}.gif`;

/* bundled Pokémon cry (Gen-1, mp3 — iOS-safe) */
const POKE_CRY = (id) => `cries/${id}.mp3`;

/* generated name-saying voice ("Pika pika! Pikachu!") — cute anime-style */
const POKE_VOICE = (id) => `voices/${id}.m4a`;
